c. BRENT...................................................................
c   THIS SUBROUTINE CALCULATES AN OPTIMAL VALUE OF MOPT AND CALLS
c   BRENTM. THE PARAMETERS ARE A SUBSET OF THOSE OF BRENTM WITH THF
c   EXCEPTION OF LWA AND WA :
c
c   LWA IS AN INTEGER GREATER THAN OR EQUAL TO N*N+3*N
c
c   WA IS A LINEAR ARRAY OF LENGTH LWA.
c .........................................................................
    SUBROUTINE BRENT(N,FCN,X,FTOL,XTOL,MAXFEV,IER,LWA,WA)
    INTEGER N,MAXFEV,IER,LWA,K,MOPT
    REAL *8 FTOL,XTOL,DKP1,EMAX,ONE,ZERO
    REAL *8 X(N),WA(LWA)
    REAL *8 DABS,DLOG
    EXTERNAL FCN
    DATA ZERO,ONE /0.D0,1.D0/
    IER = 0
    IF (N .LE. 0 .OR. LWA .LT. N*N+3*N) RETURN
    DO  10 K = 1, N
        DKP1 = ONE*(K+1)
        WA(K) = DLOG(DKP1)/(N+2*K+1)
10      CONTINUE
    EMAX = ZERO
    DO 20 K = 1, N
        IF (DABS(WA(K)) .LT. EMAX) GO TO 20
        MOPT = K
        EMAX = DABS(WA(K))
20      CONTINUE
    CALL BRENTM(N,FCN,X,FTOL,XTOL,MAXFEV,IER,MOPT,WA(3*N+1),
    + WA(2*N+1),WA(N+1),WA(1))
    RETURN
    END
c.BRENTM....................................................................
c
C   THIS SUBROUTINE TFIES TO FIN1) h ZERO TO A SYSTEM OF N SYMULTANEOlJS
C   EQtlATICNS IN N UNKNOlvNS BY BRE~T'S METHOD.
c
C   ON INPUT:
c
C       N IS THB NO~BER ·OF EQUATIO~ AND ONKNO~NS.
c
C       FCN IS THE NA~E OF THE SUBROUTINE ~HICH DEFINES THE SYSTE~
C       OF F.QU~TIO~S. TP.E USER SPECIFIES FCN BY WRITING h SUBROUTIN~
C       FCN(N,K,X,FCNK,IER) WHICH COMPUTES THE K-TH COMPONENT OF FCN
C       .EVALUATED AT X AND RETURNS THE VALUE IN FCNK. IFR SHOULD
C       NOT BE CHANGED UNLESS THE 'lSEg_ 'f~.NTS TO TERMINATE '!'HE
C       ITE~ATION. IN THIS CASE SET IE9 TO A NEGATIVE INTEGER.
c
C       X IS AN ARAY OF LENGTH N WHICH MUST CONTAIN THE INITIAL
C       . ESTIMATE TO THE ZERO OF THE SYSTE~ OF EQUATIONS.
c
C       FTOL SPECIFIES THE FIRST STOPPING CRITERION. TERMtNATION OCCURS
C       IF ALL THE RESIDU~LS ARE LESS THAN ?TOL IN M~GNITODE.
c
C       XTOL SPECIFIES T.HE SECOND STOPPr NG CRI'IERION. TERMINATION
C       OCCURS TP THE RELATIVE ERROR BETWEEN TWO SUCCESSIVE ITERATES
C       IS LESS THAN XTOL.
c
c       HAXFEV SPECIFIES THE THIRD STOPPING CRITERION. TERMINATION
c       OCCURS IF THE NUMBER OF CALLS TO FCN .EXCEEDS MAXFEV.
c
c       .MOPT IS THE NUMBER OF CONSECUTIVE TIMES THAT THE APPROXIMATE
c JACOBIAN IS REUSED DURING EACH ITERATION OF ITERATIVE
c REFINEMENT. MAXIMUM EFPICIENCY.IS USUALLY OBTAINED IF
c l'iOPT 11AXI!HZES LOG(K+1)/(N+2*K+1) FORK= 1, ••• ,N.
c ON OUTPUT:
c X CON1ATNS THE FINAL ESTIMATE FOR THE ZERO OF THE.SYSTEM
c OF EQtJATIONS.
c l1AXPEV CONTAINS THE NUMBER OF CALT,S USED IN PRODUCING X.
c IER IS SET AS FOLLOWS:
c IER=O IMPROPER INPUT PARAMeTERS.
c IER=1 "ABSOLUTE VALUE OF EACH RESIDUAL IS LESS THAN FTOL.
c IER=2
c IER=3
c IER=4
c IER=5
c IE"R=6
c IEF=7
c IER=8
c WORK! NG HRHS:
c RELATIVE ERROR BETWEEN TWO SUCCESSIVE ITERATES
c IS LESS THAN XTOL.
c CONDITIONS FOR IER=1 AND IER=2 HOLD.
c NUMBER OF CALLS TO F EXCEEDS MAXFEV.
c APPROXIMATE JACOBIAN ~ATgiX IS SINGULAR.
c ITERATION IS NOT MAK[ NG GOOD PROGRESS.
c ITERATION IS DIVERGING.
c ITERATION SEEMS TO BE CON~ERGING BUT THE REQUESTED
c ACCURACY IS TOO STRINGENT, OR THE CONVERGENCE
c IS VERY SLO~ DUE TO A JACOBIAN SINGULAR NEAR
c THE ITERATES OR DUE TO BADLY SCALED VARIABLES.
c · Q IS AN N BY N HR~Y.
c Y,Z,A ARE.LIN~AR ARAYS OF LENGTH N~
c c ...... ·. . . . . . . . .. . . . . . . . . . . . . . . . . . . . . . . . . . ............................. .
c c·
    SUBROUTINE BRENTM(N,FCN,X,FTOI,XTOL,MAXFEV,IER,MOPT,Q,Y,Z,A)
    INTEGER I,IER,J,K,M,MAXFEV,MOPT,N,NFEVAL,NIER6,NIER7,NIER8
    REAL *8 DIFIT,DIFIT1,EPS,EPSMCH,ETA,ETA1,FKZ,FNORM,FNOPM1,
    +       FONCT,FTOL,H,ONE,P05,BC,SIGMA,XNORM,XTOL,ZERO
    REAL *8 A(N),Q(N,N),X(N),Y(N),Z(N) .
    REAL *8 DMAX1,DABS,DSQRT
    LOGICAL CONV,SING
    DATA ZERO,ONE,P05 /0.D0,1.D0,5.D-2/
    IER = 0
    IF (N .LE. 0) RETURN
C
C EPSMCH IS THE MACHINE PRECISION.
C
c EPSMCH = 16.D0**(-13)
EPS = DSQRT(EPSMCH) 
c 
C NFEVAL COUNTS THE NryMRER OF COMPONENT FUNCTION EVALUATIONS. 00001210
C· XNORM IS TH~ NORM OF X. 00001220
C FNORM IS THE COMPUTED RESIDUAL WITH MAXIMUM ABSOLUT~ VALUE. 00001230
C DIFIT IS THE NOR~ OF THE DIFFERENCE BETWEEN THE LAST T~O IT~~ATES.00001240
C NIER6 IS USED TO DETERMINE WHEN TO SET IER=6. 00001250
C NIER7 IS USED TO DETERMINE WHEN TO SET IER=7. 00001260
C NIER8 IS USED TO DETERMI~E WHEN TO SET IER=8. 00001270
c 
    NFEVAL = 0 
    XNORM = ZERO 
    FNORM = ZERO 
    DIFIT = ZERO 
    NIER6 = -1 
    NIER7 = -1 
    NIER8 = 0
    DO 10 I = 1,N 
        XNORM = DMAX1(XNORM,DABS(X(I)))
10      CONTINUE
c 
C El-!TER THE PRINCIPAL I.TERATION. 00 001400
c 
20  CONTINUE
    SING    = .TRUE. 
    FNORM1  = FNORM
    FNORM   = ZRRO 
    DIFIT1  = DIFIT 
c 
C COMPUTE THE STEP H FOR THE DIVIDED DIFFERENCE WHICH 00001480
C APPROXIMATES TH~ K-TH ROW OF THE JACOBIAN MATRIX. 00001490
c 
    H = EPS*DMAX1(XNORM,ONE)
    DO 40 J = 1,N
        DO 30 I = 1,N
            Q(I,J) = ZERO
30          CONTINUE
        Q(J,J) = H
        Y(J) = X(J)
40      CONTINUE
c 
C. ENTER A SOBIT13::RA'!'ION. 00001600
c 
    DO 130 K = 1,N
        CALL FCN(N, K, Y, FONCT, IER)
        IF (ISR .LT. 0) GO TO 210
        NFEVAL = NFEVAL+1
        FNORM = DMAX1(FNORM,DABS(FONCT))
C
C       COMPUTE THE K-TH ROq OF THE JACOBIAN MATRIX.
C
        DO 60 J = K,N
            DO 50 I = 1, N
                Z(I) = Y(I)+Q(I,J)
 50             CONTINUE
            CALL FCN(N, K, Z, FKZ, IER)
            IF (IER .LT. 0) GO TO 210
            NFEVAL = NFEVAL+1
            A(J) = FKZ-FONCT
60          CONTINUE
C
C       COMPOTE THE HOUSEHOLDER TRANSFlRMATION TO REDUCE THE K-TH RO~
C       OF THE JACOBIAN MArRIX TO A MULTIPLE OF THE ~-TH UNIT VECTOR.
C
        ETA = ZERO
        DO 70 I = K,N
            ETA = DMAX1(ETA,DABS(A(I)))
70          CONTINUE
        IF (ETA .EQ. ZERO) GO TO 130
        SING = .FALSE.
        SIGMA = ZERO
        ETA1 = ONE/ETA
        DO 80 I = K,N
            A(I)  = A(I)*ETA 1
            SIGMA = SIGMA+A(I)*A(I)
80          CONTINUE
        SIGMA = DSQRT (SIG1H)
        IF (A(K) .LT. ZER0) SIGMA = -SIGMA
        A(K) = A(K) + SIGMA
C
C       APPLY THE TRANS FORM AT ION AND C) r1PUTE THE ORTHOGON.AL MATRIX Q.
C
        DO 110 I = 1, N
            RO = ZERO
            DO 90 J = K, N
                RO = RO+A(J)*Q(I,J)
90              CONTINUE
            RO = RO/(SIGMA*A(K))
            DO 100 J = K,N
                Q(I,J) = Q(I,J) - RO*A(J)
100             CONTINUE
110         CONTINUE
C
C       COMPUTE ~HE NE~ SIJBITERATE.
C
        A(K) = SIGMA*STA
        SIGMA = FONCT/A(K)
        DO 120 I = 1,N
            Y(I) = Y(I)+SIGMA*Q(I,K)
120         CONTINUE
130     CONTINUE
C
C   COMPUTE ~HE NORM OF THE ITERATE AND THE NORM OF THE DIFFERENCE
C   BETWEEN THE LAST TWO ITERATES.
C
    XNORM = ZERO
    DIFIT = ZBRO
    DO 140 I = 1,N
        XNORM = DMAX1(XNORM,DABS(Y(I)))
        DIFIT = DMAX1(DIFIT,DABS(X(I)-Y(I)))
        X(I)  = Y(I)
140     CONTINUE
C
C   DETERMINE THE PROGRESS OF TilE ITERATION.
C
    CONV = .FALSE.
    IF (FNORM .LT. FNORM .AND. DIFIT .LT. DIFIT1) CONV = .TRUE.
    NIER6 = NIER6+1
    NIER7 = NIER7+1
    NIER8 = NIER8+1
    IF (CONV) NIER6=0
    IF (FNORM .LT. FNORM1 .OR.  DIFIT .LT. DIFIT1) NIER7=0
    IF (FNORM .GT. EPS    .AND. DIFIT .GT. EPS*DMAX1(XNORM,ONE)) NIER8=0
C
C STOPPING CRITERIA.
C 
    IF (FNORM .LT. FTOL) IER=1
    IF (DIFIT .LT. XTOL*XNORM .AND. CONV) IER=2
    IF (FNORM .LT. FTOL .AND. IER .EQ. 2) IER=3
    IF (NFEVAL .GT. MAXPEV) IER=4
    IF (SING) IER=5
    IF (NIER6 .GE. 5) IER=6
    IF (NIER7 .GE. 3) IER=7
    IF (NIER8 .GE. 4) IER=8
    IF (IER .NE. 0) GO TO 210
C
C ITERATIVE REFINEMENT IS ONLY USED IF THE ITERATION IS CONVERGING.
C
    IF (.NOT. CONV .OR. DIFIT .GE. P05*XNORM) GO TO 200
C
C   START ITERATIVE REFINEMENT.
C
    IF (MOPT .EQ. 1) GO TO 200
    DO 190 H = 2,MOPT
        FNORM1 = FNORM
        FNORM  = ZERO
        DO 170 K = 1, N
            CALL FCN(N,K,Y,FONCT,IER)
            If (IER .LT. 0) GO TO 210
            NFEVAL = NFEVAL + 1
            FNORM = DMAX1(FNORM,DABS(FONCT))
C
C           ITERATIVE REFINEMENT IS TERMINATED IF IT DOES NOT .
C           GIVE A PEDUCTION OF THE RESIDUALS OR IF A(K) IS ZERO.
C
            IF (FNORM .LT. FNORM1 .AND. A(K) .NE. ZERO) GO TO 150
            FNORM = FNORM1
            GO TO 200
150         CONTINUE
            SIGMA = FONCT/A(K)
            DO 160 I = 1,N
                Y(I) = Y(I)+SIGMA*Q(I,K)
160             CONTINUE
170         CONTINUE
C
C       COMPUTE THE NORM OF T~E ITERJI.TE AND THE NORM OF THE DtFFERENCE
C       BETWEEN TH~ LAST T~O ITERAlES OF THE ITERATIVE REFINEMENT.
C
        XNORM = ZERO
        DIFIT = ZERO
        DO 180 I = 1, N
            XNORM = DMAX1(XNORM,DABS(Y(I)))
            DIFIT = DMAX1(DIFIT,DABS(X(I)-Y(I)))
            X(I) = Y(I)
180         CONTINUE
C
C       STOPPING CRITERIA FOP ITERATIVE REFINRMENT.
C
        IF (FNORM .LT. FTOL) IER= 1
        IF (DIFIT .LT. XTOL*XNORM .AND. CONV) IER=2
        IF (FNORM .LT. FTOL .AND. IER .EQ. 2) IER=3
        IF (NFEVAL .GT. MAXFEV) IER=4
        IF (IER .NE. 0) GO TO 210
190     CONTINUE
200 CONTINUE
C
C   END OF THE ITERATIVE REFINEMENT.
C
    GO TO 20
210 CONTINUE
    MAXFEV = NFEVAL
    RETURN
    END
