SUBROUTINE NS01A (N, X, F, AJINV, DSTEP, DMAX, ACC, MAXFUN, IPRINT, W)
    DIMENSION X(1),F(1), AJINV(N,N), W(1)
C SET VARIOUS PARAMETERS
    MAXC = 0
C 'MAXC' COUNTS THE NUMBER OF CALLS OF CALFUN
    NT    = N + 4
    NTEST = NT
C 'NT' AND 'NTEST' CAUSE AN ERROR RETURN IF F(X) DOES NOT DECREASE
    DTEST = FLOAT(N+N)-0.5
C ' DTEST' IS USED TO MAINTAIN LINEAR INDEPENDENCE
    NX  = N*N
    NF  = NX*N
    NW  = NF*N
    MW  = NW+N
    NDC = MW+N
    ND  = NDC+N
C THESE PARAMETERS SEPARATE THE WORKING SPACE ARRAY W
    FMIN = 0.
C USUALLY 'FMIN' IS THE LEAST CALCULATED VALUE OF FIX),
C AND THE BEST X IS IN W(NX+1) TO W(NX+N)
    DD  = 0.
C USUALLY DD IS THE SQUARE OF THE CURRENT STEP LENGTH
    DSS = DSTEP*DSTEP
    DM  = DMAX*DMAX
    DMM = 4.*DM
    IS  = 5
c 'IS' CONTROLS A 'GO TO' STATEMENT FOLLOWING A CALL OF CALFUN
    TINC = 1.
c 'TINC' IS USED IN THE CRITERION TO INCREASE THE STEP LENGTH
c START A NEW PAGE FOR PRINTING
    IF (IPRINT) 1,1,85
85  PRINT 86
86  FORMAT ( 1H1 )
c CALL THE SUBROUTINE CALFUN
1   MAXC = MAXC+l
    CALL CALFUN (N,X,F)
c TEST FOR CONVERGENCE
    FSQ = 0.
    DO 2 I = 1, N
    FSQ=FSQ+F(I)*F(I)
2   CONTINUE
    IF (FSQ-ACC) 3,3,4
C   PROVIDE PRINTING OF FINAL SOLUTION IF REQUESTED
3   IF (IPRINT) 5,5,6
6   PRINT 7, MAXC
7   FORMAT (///5X,'THE FINAL SOLUTION CALCULATED BY NSOIA REQUIRED',
    1I5,' CALLS OF CALFUN, AND IS')
    PRINT 8,(I,X(I),F(I), I = l, N)
8   FORMAT (//4X,'I',7X,'X(I)',12X,'F(I)'//(I5,2E17.8))
    PRINT 9, FSQ
9   FORMAT ( /5X , 'THE SUM OF SQUARES IS', E17.8)
5   RETURN
C   TEST FOR ERROR RETURN BECAUSE F(X! DOES NOT DECREASE
4   GO TO (10,11,11,10),IS
10  IF (FSQ-FMIN) 15,20,20
20  IF (DD-DSS) 12,12,11
12  NTEST=NTEST-1
    IF (NTEST) 13,14,11
14  PRINT 16, NT
16  FORMAT ( ///5X,'ERROR RETURN FROM NS0IA BECAUSE',I5,
    1' CALLS OF CALFUN FAILED TO IMPROVE THE RESIDUALS')
17  DO 18 I= 1, N
    X(I) = W(NX+I)
    F(I) = W(NF+I)
18  CONTINUE
    FSQ = FMIN
    GO TO 3
C   ERROR RETURN BECAUSE A NEW JACOBIAN IS UNSUCCESSFUL
13  PRINT 19
19  FORMAT ( ///5X,'ERROR RETURN FROM NSOIA BECAUSE F(X) ',
1   'FAILED TO DECREASE USING A NEW JACOBIAN')
    GO TO 17
15  NTEST = NT
C   TEST WHETHER THERE HAVE BEEN MAXFUN CALLS OF CALFUN
11  IF ( MAXFUN-MAXC ) 21,21,22
21  PRINT 23, MAXC
23  FORMAT ( ///5X ,' ERROR RETURN FROM NSOIA BECAUSE THERE HAVE BEEN',1I5,' CALLS OF CALFUN')
    IF (FSQ-FMIN) 3,17,17
C   PROVIDE PRINTING IF REQUESTED
22  IF (IPRINT) 24,24,25
25  PRINT 26, MAXC
26  FORMAT ( ///5K, 'AT THE',I5,' TH CALL OF CALFUN WE HAVE')
    PRINT 8,(I,X(I),F(I),I = 1,N)
    PRINT 9,FSQ
24  GO TO (27,28,29,87,30),IS
C   STORE THE RESULT OF THE INITIAL CALL OF CALFUN
30  FMIN = FSQ
    DO 31 I = 1, N
    W(NX+I) = X(I)
    W(NF+I) = F(I)
31  CONTINUE
C   CALCULATE A NEW JACOBIAN APPROXIMATION
32  IC = C
    IS = 3
33  IC = IC+1
    X(IC) = X(IC) + DSTEP
    GO TO 1
29  K = IC
    DO 34 I = 1, N
    W(K) = (F(I)-W(NF+I)) / DSTEP
    K = K+N
34  CONTINUE
    X(IC) = W(NX+IC)
    IF (IC-N) 33,35,35
C   CALCULATE THE INVERSE UF THE JACOBIAN AND SET THE DIRECTION MATRIX
35  K = C
    DO 36 I = 1, N
    DO 37 J = 1, N
    K = K + 1
    AJINV(I, J) = W(K)
    W(ND+K) = 0.
37  CONTINUE
    W(NDC + K + I) = i.
(0 90 W(NDC + n=l»+FLOATIN-I )
COQ] 36 CONTINUE
n. 9? CALL MB018 ( A JINV,N,N)
C START ITERATION BY PREDICTING THE DESCENT AND NEWTON MINIMA
0.(93 38 DS =0.
00 94 DN=0®
K 95 SP=O.
00 96 DO 39 1=1, N
f < 97 X( I) =0 