/*
This code was generated by the ChatGPT AI

To find the eigenvalues and eigenvectors 
of a matrix using C programming and LAPACK, 
you can use the dgeev routine from the LAPACK 
library. This routine computes the eigenvalues 
and eigenvectors of a general matrix.

To use the dgeev routine, you will first need 
to install the LAPACK library. Here is an 
example of how to do this on a Linux system:
    $ sudo dnf install liblapack-dev
For Ubuntu:
    $ sudo apt-get install liblapack-dev liblapack-doc liblapack-pic liblapack3 liblapack-test  liblapacke liblapacke-dev
---------------------------------------------
 Compile and execute with:
    > gcc eigeng.c -o eigeng -llapacke
    > ./eigeng
*/
#include <stdio.h>
#include <lapacke.h>

int main()
{
    // Define a matrix
    double A[9] = { 1, 2, 3, 
                    4, 5, 6, 
                    7, 8, 9 };

    // Compute the eigenvalues and eigenvectors of the matrix
    char jobvl = 'N'; // don't compute left eigenvectors
    char jobvr = 'V'; // compute right eigenvectors
    lapack_int n = 3; // size of the matrix
    lapack_int lda = 3; // leading dimension of the matrix
    double wr[3]; // array to store the real part of the eigenvalues
    double wi[3]; // array to store the imaginary part of the eigenvalues
    double vl[3*3]; // array to store the left eigenvectors (not used)
    lapack_int ldvl = 3; // leading dimension of the left eigenvectors (not used)
    double vr[3*3]; // array to store the right eigenvectors
    lapack_int ldvr = 3; // leading dimension of the right eigenvectors
    lapack_int info; // variable to store the error code

    // Compute the eigenvalues and eigenvectors
    info = LAPACKE_dgeev(LAPACK_ROW_MAJOR, jobvl, jobvr, n, A, lda, wr, wi, vl, ldvl, vr, ldvr);
    if (info != 0) {
        fprintf(stderr, "LAPACKE_dgeev failed with error %d\n", info);
        return 1;
    }

    // Print the eigenvalues
    printf("Eigenvalues: %f %f %f\n", wr[0], wr[1], wr[2]);

    // Print the eigenvectors
    printf("Eigenvectors:\n");
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < n; j++) {
            printf("%f ", vr[i*ldvr + j]);
        }
        printf("\n");
    }

    return 0;
}
