#!/usr/bin/env python3
"""
Plot and compare ODE solver results from C++ program
Reads .dat files generated by the ODE solver library
"""

import numpy as np
import matplotlib.pyplot as plt
import os

def exact_solution(t):
    """
    Exact solution: y(t) = (t^2 + 2t + 4) / 2
    """
    return (t**2 + 2*t + 4) / 2

def read_dat_file(filename):
    """
    Read time and y values from .dat file
    """
    if not os.path.exists(filename):
        print(f"Warning: File {filename} not found")
        return None, None
    
    data = np.loadtxt(filename)
    t = data[:, 0]
    y = data[:, 1]
    return t, y

def plot_all_solutions():
    """
    Create comprehensive plots comparing all methods and step sizes
    """
    step_sizes = [0.1, 0.05, 0.01, 0.001]
    
    # Create exact solution for reference
    t_exact = np.linspace(0, 1, 1000)
    y_exact = exact_solution(t_exact)
    
    # Figure 1: Compare Forward Euler with different step sizes
    plt.figure(figsize=(14, 10))
    
    # Subplot 1: Forward Euler methods
    plt.subplot(2, 2, 1)
    plt.plot(t_exact, y_exact, 'k-', linewidth=2, label='Exact Solution')
    
    for h in step_sizes:
        filename = f"euler_h{h:.6f}.dat"
        t, y = read_dat_file(filename)
        if t is not None:
            plt.plot(t, y, 'o-', markersize=2, label=f'Euler h={h}')
    
    plt.xlabel('Time t', fontsize=12)
    plt.ylabel('y(t)', fontsize=12)
    plt.title('Forward Euler Method - Different Step Sizes', fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    # Subplot 2: Runge-Kutta 4 methods
    plt.subplot(2, 2, 2)
    plt.plot(t_exact, y_exact, 'k-', linewidth=2, label='Exact Solution')
    
    for h in step_sizes:
        filename = f"rk4_h{h:.6f}.dat"
        t, y = read_dat_file(filename)
        if t is not None:
            plt.plot(t, y, 's-', markersize=2, label=f'RK4 h={h}')
    
    plt.xlabel('Time t', fontsize=12)
    plt.ylabel('y(t)', fontsize=12)
    plt.title('Runge-Kutta 4 Method - Different Step Sizes', fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    # Subplot 3: Error comparison for h=0.1
    plt.subplot(2, 2, 3)
    h = 0.1
    
    # Forward Euler
    filename = f"euler_h{h:.6f}.dat"
    t_euler, y_euler = read_dat_file(filename)
    if t_euler is not None:
        error_euler = np.abs(y_euler - exact_solution(t_euler))
        plt.semilogy(t_euler, error_euler, 'o-', label=f'Euler h={h}')
    
    # Runge-Kutta 4
    filename = f"rk4_h{h:.6f}.dat"
    t_rk4, y_rk4 = read_dat_file(filename)
    if t_rk4 is not None:
        error_rk4 = np.abs(y_rk4 - exact_solution(t_rk4))
        plt.semilogy(t_rk4, error_rk4, 's-', label=f'RK4 h={h}')
    
    plt.xlabel('Time t', fontsize=12)
    plt.ylabel('Absolute Error', fontsize=12)
    plt.title(f'Error Comparison (h={h})', fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    # Subplot 4: Final error vs step size
    plt.subplot(2, 2, 4)
    
    euler_errors = []
    rk4_errors = []
    valid_h = []
    
    for h in step_sizes:
        # Forward Euler
        filename = f"euler_h{h:.6f}.dat"
        t, y = read_dat_file(filename)
        if t is not None and len(t) > 0:
            final_error_euler = np.abs(y[-1] - exact_solution(t[-1]))
            euler_errors.append(final_error_euler)
        else:
            euler_errors.append(np.nan)
        
        # Runge-Kutta 4
        filename = f"rk4_h{h:.6f}.dat"
        t, y = read_dat_file(filename)
        if t is not None and len(t) > 0:
            final_error_rk4 = np.abs(y[-1] - exact_solution(t[-1]))
            rk4_errors.append(final_error_rk4)
            valid_h.append(h)
        else:
            rk4_errors.append(np.nan)
    
    plt.loglog(step_sizes, euler_errors, 'o-', linewidth=2, markersize=8, label='Forward Euler')
    plt.loglog(step_sizes, rk4_errors, 's-', linewidth=2, markersize=8, label='Runge-Kutta 4')
    
    # Add reference lines for order of convergence
    if len(valid_h) > 0:
        h_ref = np.array(step_sizes)
        # First order reference
        ref1 = euler_errors[0] * (h_ref / step_sizes[0])
        plt.loglog(h_ref, ref1, 'k--', alpha=0.5, label='O(h) reference')
        # Fourth order reference
        ref4 = rk4_errors[0] * (h_ref / step_sizes[0])**4
        plt.loglog(h_ref, ref4, 'k:', alpha=0.5, label='O(h⁴) reference')
    
    plt.xlabel('Step Size h', fontsize=12)
    plt.ylabel('Final Error at t=1', fontsize=12)
    plt.title('Convergence Analysis', fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3, which='both')
    
    plt.tight_layout()
    plt.savefig('ode_comparison.png', dpi=300, bbox_inches='tight')
    print("Saved: ode_comparison.png")
    plt.show()

def plot_single_comparison(h=0.01):
    """
    Create a detailed comparison plot for a single step size
    """
    plt.figure(figsize=(14, 5))
    
    # Create exact solution
    t_exact = np.linspace(0, 1, 1000)
    y_exact = exact_solution(t_exact)
    
    # Subplot 1: Solution comparison
    plt.subplot(1, 2, 1)
    plt.plot(t_exact, y_exact, 'k-', linewidth=2, label='Exact Solution')
    
    # Forward Euler
    filename = f"euler_h{h:.6f}.dat"
    t_euler, y_euler = read_dat_file(filename)
    if t_euler is not None:
        plt.plot(t_euler, y_euler, 'ro-', markersize=3, label=f'Forward Euler (h={h})')
    
    # Runge-Kutta 4
    filename = f"rk4_h{h:.6f}.dat"
    t_rk4, y_rk4 = read_dat_file(filename)
    if t_rk4 is not None:
        plt.plot(t_rk4, y_rk4, 'bs-', markersize=3, label=f'Runge-Kutta 4 (h={h})')
    
    plt.xlabel('Time t', fontsize=12)
    plt.ylabel('y(t)', fontsize=12)
    plt.title(f'Solution Comparison (h={h})', fontsize=14, fontweight='bold')
    plt.legend(fontsize=10)
    plt.grid(True, alpha=0.3)
    
    # Subplot 2: Error plot
    plt.subplot(1, 2, 2)
    
    if t_euler is not None:
        error_euler = np.abs(y_euler - exact_solution(t_euler))
        plt.semilogy(t_euler, error_euler, 'ro-', markersize=6, label='Forward Euler Error')
    
    if t_rk4 is not None:
        error_rk4 = np.abs(y_rk4 - exact_solution(t_rk4))
        plt.semilogy(t_rk4, error_rk4, 'bs-', markersize=6, label='Runge-Kutta 4 Error')
    
    plt.xlabel('Time t', fontsize=12)
    plt.ylabel('Absolute Error', fontsize=12)
    plt.title(f'Error Analysis (h={h})', fontsize=14, fontweight='bold')
    plt.legend(fontsize=10)
    plt.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(f'ode_comparison_h{h}.png', dpi=300, bbox_inches='tight')
    print(f"Saved: ode_comparison_h{h}.png")
    plt.show()

def print_error_table():
    """
    Print a formatted table of errors for different step sizes
    """
    step_sizes = [0.1, 0.05, 0.01, 0.001]
    
    print("\n" + "="*70)
    print("ERROR ANALYSIS TABLE")
    print("="*70)
    print(f"{'Step Size':>12} | {'Euler Error':>15} | {'RK4 Error':>15} | {'Ratio':>10}")
    print("-"*70)
    
    for h in step_sizes:
        # Forward Euler
        filename = f"euler_h{h:.6f}.dat"
        t, y = read_dat_file(filename)
        if t is not None and len(t) > 0:
            euler_error = np.abs(y[-1] - exact_solution(t[-1]))
        else:
            euler_error = np.nan
        
        # Runge-Kutta 4
        filename = f"rk4_h{h:.6f}.dat"
        t, y = read_dat_file(filename)
        if t is not None and len(t) > 0:
            rk4_error = np.abs(y[-1] - exact_solution(t[-1]))
        else:
            rk4_error = np.nan
        
        ratio = euler_error / rk4_error if rk4_error > 0 else np.nan
        
        print(f"{h:>12.6f} | {euler_error:>15.8e} | {rk4_error:>15.8e} | {ratio:>10.2f}")
    
    print("="*70)
    print("Note: Ratio shows how many times more accurate RK4 is than Euler")
    print("="*70 + "\n")

if __name__ == "__main__":
    print("ODE Solution Plotter")
    print("=" * 50)
    
    # Check if data files exist
    step_sizes = [0.1, 0.05, 0.01, 0.001]
    files_found = 0
    
    for h in step_sizes:
        if os.path.exists(f"euler_h{h:.6f}.dat"):
            files_found += 1
        if os.path.exists(f"rk4_h{h:.6f}.dat"):
            files_found += 1
    
    if files_found == 0:
        print("\nError: No .dat files found!")
        print("Please run the C++ program first to generate data files.")
    else:
        print(f"\nFound {files_found} data files\n")
        
        # Print error table
        print_error_table()
        
        # Create comprehensive plots
        print("Creating comprehensive comparison plots...")
        plot_all_solutions()
        
        # Create detailed plot for h=0.01
        print("\nCreating detailed comparison for h=0.01...")
        plot_single_comparison(h=0.01)
        
        print("\nAll plots created successfully!")